name: farm_manager
description: Farm Manager application
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  excel: ^4.0.6
  pdf: ^3.11.3
  shared_preferences: ^2.5.5
  image_picker: ^1.2.3
  share_plus: ^10.1.4

dev_dependencies:
  flutter_launcher_icons: ^0.14.3

  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true


flutter_launcher_icons:
  android: true
  ios: true
  web:
    generate: true
    image_path: assets/ali_goat_farm_icon.svg
    background_color: "#12372A"
  image_path: assets/ali_goat_farm_icon.svg
  adaptive_icon_background: "#12372A"
